service: fetch-file-and-store-in-s3

custom:
  bucket: S3Bucket

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  deploymentPrefix: serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  save:
    handler: handler.save
    environment:
      BUCKET: ${self:custom.bucket}

# resources:
#   Resources:
#     S3BucketOutputs:
#       Type: AWS::S3::Bucket
#       Properties: 
#         BucketName: ${self:custom.bucket}